### PR TITLE
Fix for undefined method presence

### LINKED ISSUE #16: The new kube train fails to work as advertised
inspect detect with the new train (k8s-container) FAILS 

For example, running the following: 
❯ inspec detect -t k8s-container://kube-system/aws-node-bfbhd/aws-node
... results in: 
/Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/connection.rb:16:in `initialize': **undefined method `presence' for "kube-system":String (NoMethodError)**

# Describe the problem

Followed the installation instructions for the new kube k8s train, and tried to execute the "inspec detect -t k8s-container://<namespace/pod/container>" ... which failed.  Details below : 

1. First, cloned the repo : 
❯ git clone https://github.com/inspec/train-k8s-container.git

2. Next, ran the plugin install command: 
 ❯ inspec plugin install /Users/[username]/test/inspec2/train-k8s-container
... which succeeded 

3. Finally, attempted the "inspec detect -t k8s-container:// " command on an arbitrary namespace/pod/container, which FAILED with the following error: 
❯ inspec detect -t k8s-container://kube-system/aws-node-bfbhd/aws-node

/Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/connection.rb:16:in `initialize': **undefined method `presence' for "kube-system":String (NoMethodError)**
      from /Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/transport.rb:14:in `new'
      from /Users/[USERNAME]/test/inspec2/train-k8s-container/lib/train/k8s/container/transport.rb:14:in `connection'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/backend.rb:38:in `create'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/runner.rb:89:in `configure_transport'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/runner.rb:81:in `initialize'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/cli.rb:517:in `new'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/cli.rb:517:in `run_command'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/cli.rb:382:in `detect'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.22.3/lib/inspec/base_cli.rb:35:in `start'
      from /opt/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-bin-5.22.3/bin/inspec:11:in `<top (required)>'
      from /usr/local/bin/inspec:275:in `load'
      from /usr/local/bin/inspec:275:in `<main>'

----

Tried this with other  namespace/pod/container ... all of which failed with the same error:  
... **undefined method `presence' for "<namespace>":String (NoMethodError)**

### PR DESCRIPTION
**Pull request by Vasu1105**
## Description

Fixes #16 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: lib/train/k8s/container/connection.rb [hunk 1]
```diff
@@ -8,12 +8,16 @@ class Connection < Train::Plugins::Transport::BaseConnection
 
         # URI format: k8s-container://<namespace>/<pod>/<container_name>
         # @example k8s-container://default/shell-demo/nginx
+
+        DEFAULT_NAMESPACE = "default"
```
Comment (sathish-progress) [inline lib/train/k8s/container/connection.rb:12]: actually this is not needed.. we already have `Train::K8s::Container::KubectlExecClient::DEFAULT_NAMESPACE`

File: lib/train/k8s/container/kubectl_exec_client.rb [hunk 2]
```diff
@@ -8,12 +8,10 @@ module Container
       class KubectlExecClient
         attr_reader :pod, :container_name, :namespace
 
-        DEFAULT_NAMESPACE = "default".freeze
-
         def initialize(pod:, namespace: nil, container_name: nil)
           @pod = pod
           @container_name = container_name
-          @namespace = namespace || DEFAULT_NAMESPACE
+          @namespace = namespace
```
Comment (sathish-progress) [inline lib/train/k8s/container/kubectl_exec_client.rb:14]: so the default namespace logic is kept here because it is the responsibility of the kubectl client to be aware of the connection internal details of the cluster.. so I would keep this logic in here

File: lib/train/k8s/container/connection.rb [hunk 3]
```diff
@@ -8,12 +8,16 @@ class Connection < Train::Plugins::Transport::BaseConnection
...
+
         def initialize(options)
           super(options)
           uri_path = options[:path]&.gsub(%r{^/}, "")
           @pod = options[:pod] || uri_path&.split("/")&.first
           @container_name = options[:container_name] || uri_path&.split("/")&.last
-          @namespace = options[:namespace] || options[:host]&.presence
+          host = options[:host] unless options[:host].nil? || options[:host].empty?
+          @namespace = options[:namespace] || host || DEFAULT_NAMESPACE
```
Comment (sathish-progress) [inline lib/train/k8s/container/connection.rb:20]:
```suggestion
           host = (!options[:host].nil? && !options[:host].empty?) ? options[:host] : nil
           @namespace = options[:namespace] || host
```

File: lib/train/k8s/container/kubectl_exec_client.rb (hunk 2 above)
Comment (Vasu1105) [reply lib/train/k8s/container/kubectl_exec_client.rb:14]: But isn't that good to keep all connection parameters together with default values? When I look at the code I am expecting if namespace OR host is not provided it should assign default namespace before connection happens.  I had to run through all flow to understand if those two parameters are not available then what's the default getting assigned.

Comment (sathish-progress) [reply lib/train/k8s/container/kubectl_exec_client.rb:14]: yeah because it is the responsibility of the K8s client .. not train transport connection

Comment (sathish-progress) [reply lib/train/k8s/container/kubectl_exec_client.rb:14]: one thing if you want to do like this https://github.com/inspec/train-k8s-container/pull/17/files#diff-c4540897f7e17865b4c727a6a2549a98746fa379c627f8cd12cc248b14e1d1cbR20, 

then you can do `host || Train::K8s::Container::KubectlExecClient::DEFAULT_NAMESPACE`
